---
- name: Check OS ( OKD )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-mgr-facts.yml
  tags:
    - install
    - uninstall


- name: Configure OKD Manager
  import_tasks: configure-okd-mgr.yml
  tags: install
  when: inventory_hostname in groups['manager']


#- name: Install OKD Manager
#  import_tasks: install-okd-mgr.yml
#  tags: install
#  when: inventory_hostname in groups['manager']


- name: Uninstall OKD Manager
  import_tasks: uninstall-okd-mgr.yml
  tags: uninstall
  when: inventory_hostname in groups['manager']

