---
- name: Check OS ( OKD )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-mgr-facts.yml
  tags:
    - prepare
    - install
    - uninstall


- name: Prepare OKD Manager
  import_tasks: config-okd-mgr.yml
  tags: prepare
  when: inventory_hostname in groups['manager']


- name: Install OKD Install Cleint
  import_tasks: install-okd-client.yml
  tags: install
  when: install_okd_client is defined and install_okd_client == true and inventory_hostname in groups['master']


- name: Install CoreOS BootStrap
  import_tasks: install-bootstrap.yml
  tags: install
  when: install_bootstrap is defined and install_bootstrap == true and inventory_hostname in groups['bootstrap']


- name: Install CoreOS Master
  import_tasks: install-master.yml
  tags: install
  when: install_master is defined and install_master == true and inventory_hostname in groups['master']


- name: Uninstall OKD Install Cleint
  import_tasks: uninstall-okd-client.yml
  tags: uninstall
  when: uninstall_okd_client is defined and uninstall_okd_client == true and inventory_hostname in groups['master']


#- name: Install OKD Manager
#  import_tasks: install-okd-mgr.yml
#  tags: install
#  when: inventory_hostname in groups['manager']


- name: Uninstall OKD Manager
  import_tasks: uninstall-okd-mgr.yml
  tags: uninstall
  when: inventory_hostname in groups['master']

