---
- name: Check OS ( OKD )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-okd-facts.yml
  tags: install, uninstall, deploy, destory, setup, remove


- name: Setup Network
  import_tasks: install-network.yml
  tags: setup, install
  when: ( network is defined and network == true )


- name: Setup DNSMasq
  import_tasks: setup-dnsmasq.yml
  tags: setup, install
  when: ( dnsmasq is defined and dnsmasq == true )


- name: Setup Resolved
  import_tasks: setup-resolved.yml
  tags: setup, install
  when: ( resolved is defined and resolved == true )


- name: Remove Resolved
  import_tasks: remove-resolved.yml
  tags: remove, uninstall
  when: ( resolved is defined and resolved == true )


- name: Remove DNSMasq
  import_tasks: remove-dnsmasq.yml
  tags: remove, uninstall
  when: ( dnsmasq is defined and dnsmasq == true )


- name: Remove Network
  import_tasks: remove-network.yml
  tags: remove, uninstall
  when: ( network is defined and network == true )


- name: Setup OKD Manager
  import_tasks: install-mgr.yml
  tags: setup, install
  when: ( mgr is defined and mgr == true ) and inventory_hostname in groups['manager']


- name: Install OKD Install Cleint
  import_tasks: install-client.yml
  tags: setup, install
  when: ( client is defined and client == true ) and inventory_hostname in groups['manager']


- name: Install CoreOS BootStrap
  import_tasks: install-bootstrap.yml
  tags: setup, install
  when: ( bootstrap is defined and bootstrap == true ) and inventory_hostname in groups['_bootstrap']


- name: Install CoreOS Master
  import_tasks: install-master.yml
  tags: install
  when: ( master is defined and master == true ) and inventory_hostname in groups['master']


- name: Install CoreOS Worker
  import_tasks: install-worker.yml
  tags: install
  when: ( worker is defined and worker == true ) and inventory_hostname in groups['compute']


- name: Config DNS Zone and Record
  import_tasks: config-freeipa.yml
  tags: config
  when: ( freeipa is defined and freeipa == true ) and inventory_hostname in groups['dns']


- name: Uninstall OKD Install Cleint
  import_tasks: uninstall-client.yml
  tags: delete, remove, uninstall
  when: ( client is defined and client == true ) and inventory_hostname in groups['manager']


- name: Uninstall OKD Manager
  import_tasks: uninstall-mgr.yml
  tags: uninstall
  when: ( mgr is defined and mgr == true ) and inventory_hostname in groups['manager']


- name: Back to CentOS
  import_tasks: back-to-centos.yml
  tags: config, return
  when: ( centos is defined and centos == true ) and inventory_hostname in groups['master']


- name: Remove DNS Zone and Record
  import_tasks: remove-freeipa.yml
  tags: remove, delete
  when: ( freeipa is defined and freeipa == true ) and inventory_hostname in groups['dns']

