---
# Install OKD that is the upstream version of Red Hat OpenShift.
# This example is based on the environment like follows.
# --------------+----------------+-----------------+--------------
#               |192.168.1.181   |                 |192.168.1.182
# +-------------+-------------+  |  +--------------+-------------+
# |  [mgr.jtest.pivotal.io]   |  |  |[bootstrap.jtest.pivotal.io]|
# |        Manager Node       |  |  |       Bootstrap Node       |
# |           DNS             |  |  |                            |
# |          Nginx            |  |  |                            |
# +---------------------------+  |  +----------------------------+
#                                |
# --------------+----------------+-----------------+--------------
#               |192.168.1.183   |                 |192.168.1.184
# +-------------+-------------+  |  +--------------+-------------+
# |[master01.jtest.pivotal.io]|  |  |[master02.jtest.pivotal.io] |
# |      Control Plane#1      |  |  |      Control Plane#2       | 
# |                           |  |  |                            |
# |                           |  |  |                            |
# +---------------------------+  |  +----------------------------+
#                                |
# --------------+----------------+
#               |192.168.1.185
# +-------------+-------------+
# |[master03.jtest.pivotal.io]|
# |      Control Plane#3      |
# |                           |
# |                           |
# +---------------------------+
#
#
# The system minimum requirements are follows. ( By Official Doc )
#
#  * Bootstrap Node      ⇒ 4 CPU, 16 GB RAM, 100 GB Storage, Fedora CoreOS
#  * Control Plane Node  ⇒ 4 CPU, 16 GB RAM, 100 GB Storage, Fedora CoreOS
#  * Compute Node        ⇒ 2 CPU,  8 GB RAM, 100 GB Storage, Fedora CoreOS
#
# * Bootstrap Node is needed only when bootstraping cluster.
# Configure Manager Node first like here, next, Create ignition file on Manager Node like follows.


- name: Check OS ( OKD Master )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-master-facts.yml
  tags:
    - install
    - uninstall


- name: Configure OKD Master
  import_tasks: configure-okd-master.yml
  tags: install
  when: inventory_hostname in groups['master']


#- name: Install OKD Master
#  import_tasks: install-okd-master.yml
#  tags: install
#  when: inventory_hostname in groups['master']


- name: Uninstall OKD Master
  import_tasks: uninstall-okd-master.yml
  tags: uninstall
  when: inventory_hostname in groups['master']


