---
- name: Check OS ( OKD )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-okd-facts.yml
  tags:
    - install
    - uninstall


- name: Install Network
  import_tasks: install-network.yml
  tags: install
  when: install_network is defined and install_network == true


- name: Uninstall Network
  import_tasks: uninstall-network.yml
  tags: uninstall
  when: uninstall_network is defined and uninstall_network == true


- name: Prepare OKD Manager
  import_tasks: install-mgr.yml
  tags: install
  when: install_mgr is defined and install_mgr == true and inventory_hostname in groups['manager']


- name: Install OKD Install Cleint
  import_tasks: install-client.yml
  tags: install
  when: install_client is defined and install_client == true and inventory_hostname in groups['manager']


- name: Install CoreOS BootStrap
  import_tasks: install-bootstrap.yml
  tags: install
  when: install_bootstrap is defined and install_bootstrap == true and inventory_hostname in groups['bootstrap']


- name: Install CoreOS Master
  import_tasks: install-master.yml
  tags: install
  when: install_master is defined and install_master == true and inventory_hostname in groups['master']


- name: Install CoreOS Worker
  import_tasks: install-worker.yml
  tags: install
  when: install_worker is defined and install_worker == true and inventory_hostname in groups['compute']


- name: Uninstall OKD Install Cleint
  import_tasks: uninstall-client.yml
  tags: uninstall
  when: uninstall_client is defined and uninstall_client == true and inventory_hostname in groups['manager']


- name: Uninstall OKD Manager
  import_tasks: uninstall-mgr.yml
  tags: uninstall
  when: uninstall_mgr is defined and uninstall_mgr == true and inventory_hostname in groups['manager']

